src/Entity/Eleve.php
<?php

namespace App\Entity;

use App\Repository\EleveRepository;
use Doctrine\ORM\Mapping as ORM;
use Smfony\Component\Validator\Constrains as Assert;

/**
 * @ORM\Entity(repositoryClass=EleveRepository::class)
 */
class Eleve
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $classe;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_parent;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    /**
     * @ORM\Column(type="integer")
     */
    private $montant;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $matricule;

    /**
     * @ORM\Column(type="date")
     */
    private $date_inscription;

    /**
     * @ORM\Column(type="date")
     */
    private $date_derniere_modif;

    /**
     * @ORM\Column(type="boolean")
     */
    private $statut;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getClasse(): ?string
    {
        return $this->classe;
    }

    public function setClasse(string $classe): self
    {
        $this->classe = $classe;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getNumeroParent(): ?string
    {
        return $this->numero_parent;
    }

    public function setNumeroParent(string $numero_parent): self
    {
        $this->numero_parent = $numero_parent;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getMontant(): ?int
    {
        return $this->montant;
    }

    public function setMontant(int $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): self
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

    public function getDateDerniereModif(): ?\DateTimeInterface
    {
        return $this->date_derniere_modif;
    }

    public function setDateDerniereModif(\DateTimeInterface $date_derniere_modif): self
    {
        $this->date_derniere_modif = $date_derniere_modif;

        return $this;
    }

    public function getStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(bool $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    
}

src/Controller/InscriptionsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Eleve;
use App\Repository\UserRepository;
use App\Repository\EleveRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Form\EleveType;
use App\Form\SupprimerEleveType;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

class InscriptionsController extends AbstractController
{
    
    /**
     * @Route("/inscriptions", name="inscriptions")
     */
    public function index(Request $request, EleveRepository $eleveRepository, TranslatorInterface $translator)
    {
        $auth_checker = $this->get('security.authorization_checker');
        $token = $this->get('security.token_storage')->getToken();
        $user = $token->getUser();
        if($auth_checker && $user != "anon."){
            $eleve = new Eleve();
            $error="";
            $form = $this->createForm(EleveType::class, $eleve);
            $form->handleRequest($request);
            $formSupprimer = $this->createForm(SupprimerEleveType::class, $eleve);
            $formSupprimer->handleRequest($request);
    
            if($form->isSubmitted() && $form->isValid()){
                $eleve->setMatricule($this->random(10));
                $eleve->setStatut(true);
                $eleve->setDateInscription(new \DateTime('now'));
                $eleve->setDateDerniereModif(new \DateTime('now'));
    
                if($eleve->getMontant() < 5000){
                    $error= $translator->trans("Le montant de l'inscription ne doit pas être inférieur à 5000 !");
                }
                else{
                    if($eleve->getPhoto() == "" || $eleve->getPhoto() == null ){
                        $eleve->setPhoto("/uploads/eleve/photos/default_photo.jpg");
                    }
                    else{
                        $file = $form['photo']->getData();
                        $directory="../public/uploads/eleve/photos/";
                        $extension = $file->guessExtension();
                        if (!$extension) {
                           // extension cannot be guessed
                           $extension = 'bin';
                        }
                        $newFileName = $this->random(20).'.'.$extension;
                        $file->move($directory, $newFileName);
                        $eleve->setPhoto("/uploads/eleve/photos/".$newFileName);
                    }
                    $en = $this->getDoctrine()->getManager();
                    $en->persist($eleve);
                    $en->flush();
                }
            }
            if($error != ""){
                $this->addFlash('message', $error);
            }
            
            $listTitle = $translator->trans("Liste des élèves inscrits :");
            return $this->render('inscriptions/index.html.twig', [
                'controller_name' => 'InscriptionsController',
                'form' => $form->createView(),
                'formSupprimer' => $formSupprimer->createView(),
                'error' => $error,
                'eleves' => $eleveRepository->findByStatut(true),
                'list_title' => $listTitle
            ]);
        }
        else{
            return $this->redirectToRoute("app_login");
        }
    }

    /**
     * @Route("/inscriptions/supprimerEleve/{id}", name="supprimer")
     */

    public function supprimerEleve($id, EleveRepository $eleveRepository)
    {
        $auth_checker = $this->get('security.authorization_checker');
        $token = $this->get('security.token_storage')->getToken();
        $user = $token->getUser();
        if($auth_checker && $user != "anon."){
            $entityManager = $this->getDoctrine()->getManager();
        $eleve = $entityManager->getRepository(Eleve::class)->find($id);
    
        if (!$eleve) {
            throw $this->createNotFoundException(
                'No eleve found for id '.$id
            );
        }
    
        $eleve->setStatut(false);
        $entityManager->flush();
    
        $form = $this->createForm(EleveType::class, new Eleve);
    
        return $this->redirectToRoute("inscriptions");  
        }
        else{
            return $this->redirectToRoute("app_login");
        }
    }

    /**
     * @Route("/inscriptions/editerEleve/{id}", name="editer")
     */

    public function editerEleve(Request $request, EleveRepository $eleveRepository)
    {
        $auth_checker = $this->get('security.authorization_checker');
        $token = $this->get('security.token_storage')->getToken();
        $user = $token->getUser();
        if($auth_checker && $user != "anon."){
            if ($request->getMethod() == 'POST') {
                  
                $post = $request->request;
                    $entityManager = $this->getDoctrine()->getManager();
                    $eleve = $entityManager->getRepository(Eleve::class)->find($post->get('id'));
    
        if (!$eleve) {
            throw $this->createNotFoundException(
                'No eleve found for id '.$id
            );
        }
        if($post->get('photo') != null){
            $file = $post->get('photo');
                        $directory="../public/uploads/eleve/photos/";
                        $extension = $file->guessExtension();
                        if (!$extension) {
                           // extension cannot be guessed
                           $extension = 'bin';
                        }
                        $newFileName = $this->random(20).'.'.$extension;
                        $file->move($directory, $newFileName);
                        $eleve->setPhoto("/uploads/eleve/photos/".$newFileName);
        }
    
        if($post->get('date_naissance') != null){
            
            $eleve->setDateNaissance(new \DateTime($post->get('date_naissance')));
        }
        if($post->get('nom') != null || $post->get('nom')!=""){
            $eleve->setNom($post->get('nom'));
        }
        if($post->get('prenom') != null || $post->get('prenom')!=""){
            $eleve->setPrenom($post->get('prenom'));
        }
        if($post->get('classe') != null || $post->get('classe')!=""){
            $eleve->setClasse($post->get('classe'));
        }
        if($post->get('numero_parent') != null || $post->get('numero_parent')!=""){
            $eleve->setNumeroParent($post->get('numero_parent'));
        }
        
        $eleve->setDateDerniereModif(new \DateTime('now'));
        $entityManager->flush();    
        }  
            
    
        return $this->redirectToRoute("inscriptions"); 
        }
        else{
            return $this->redirectToRoute("app_login");
        }
    }

    /**
     * @Route("/inscriptions/rechercherEleve", name="rechercher")
     */

    public function rechercherEleve(Request $request, EleveRepository $eleveRepository, TranslatorInterface $translator)
    {
        $eleve = new Eleve();
            $error="";
            $form = $this->createForm(EleveType::class, $eleve);
            $form->handleRequest($request);
            $formSupprimer = $this->createForm(SupprimerEleveType::class, $eleve);
            $formSupprimer->handleRequest($request);

        $auth_checker = $this->get('security.authorization_checker');
        $token = $this->get('security.token_storage')->getToken();
        $user = $token->getUser();
        if($auth_checker && $user != "anon."){
            if ($request->getMethod() == 'POST') {
                  
                $post = $request->request;
                    $entityManager = $this->getDoctrine()->getManager();
                    $eleves = $entityManager->getRepository(Eleve::class)->findByNom($post->get('nom'));
    
        if (!$eleves) {
            $eleves = $entityManager->getRepository(Eleve::class)->findByPrenom($post->get('nom'));
            if(!$eleves){
                $eleves = $entityManager->getRepository(Eleve::class)->findByMatricule($post->get('nom'));
                if(!$eleves){
                    $eleves = $entityManager->getRepository(Eleve::class)->findByClasse($post->get('nom'));
                    if(!$eleves){
                        $message = $translator->trans("Aucun élève trouvé au nom/prénom/matricule/classe de : ");
                        $error = $message.$post->get('nom');
                        }
                }
            }
        }
        if(!$eleves){
            $message = $translator->trans("Résultat de la recherche pour le nom/prénom/matricule/classe : ");
            $listTitle = $message.$post->get('nom');
            return $this->render('inscriptions/index.html.twig', [
                'controller_name' => 'InscriptionsController',
                'form' => $form->createView(),
                'formSupprimer' => $formSupprimer->createView(),
                'error' => $error,
                'eleves' => $eleves,
                'list_title' => $listTitle
            ]);  
        }
        else{
            $message = $translator->trans("Résultat de la recherche pour le nom/prénom/matricule/classe : ");
            $listTitle = $message.$post->get('nom');
            $entityManager->flush(); 
            return $this->render('inscriptions/index.html.twig', [
                'controller_name' => 'InscriptionsController',
                'form' => $form->createView(),
                'formSupprimer' => $formSupprimer->createView(),
                'error' => $error,
                'eleves' => $eleves,
                'list_title' => $listTitle
            ]);
        }   
        }  
        }
        else{
            return $this->redirectToRoute("app_login");
        }
    }

templates/inscriptions/index.html.twig
{% extends 'main.html.twig' %}

{% block title %}Hello InscriptionsController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<p style="color: red;">{{ error }}</p>
<h2>{{ list_title }}</h2>
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">{% trans %}Matricule{% endtrans %}</th>
      <th scope="col">{% trans %}Nom{% endtrans %}</th>
      <th scope="col">{% trans %}Prénom{% endtrans %}</th>
      <th scope="col">{% trans %}Classe{% endtrans %}</th>
      <th scope="col">{% trans %}Date de naissance{% endtrans %}</th>
      <th scope="col">{% trans %}Numéro du parent{% endtrans %}</th>
      <th scope="col">{% trans %}Actions{% endtrans %}</th>
    </tr>
  </thead>
  <tbody>
  {% for eleve in eleves %}
    <tr>
      <th scope="row">#</th>
      <td>{{eleve.matricule}}</td>
      <td>{{eleve.nom}}</td>
      <td>{{eleve.prenom}}</td>
      <td>{{eleve.classe}}</td>
      <td>{{eleve.DateNaissance|date('d-m-Y')}}</td>
      <td>{{eleve.getNumeroParent()}}</td>
      <td>
         <button type="button" class="btn btn-success" data-toggle="modal" data-target="#{{eleve.matricule}}voir">{% trans %}Voir{% endtrans %}</button>
         <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#{{eleve.matricule}}editer">{% trans %}Editer{% endtrans %}</button>
         <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#{{eleve.matricule}}supprimer">{% trans %}Supprimer{% endtrans %}</button>
      </td>
    </tr>
    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="{{eleve.matricule}}voir">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{% trans %}Voir{% endtrans %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="card">
  <div class="card-header">
    {% trans %}Noms et prenoms{% endtrans %} : <strong>{{eleve.nom}}  {{eleve.prenom}}</strong>
  </div>
  <div class="card-body">
  <div class="row">
  <div class="col-md-7">
    <h5 class="card-title">{% trans %}Matricule{% endtrans %} : {{ eleve.matricule }}</h5>
    <p class="card-text">{% trans %}Classe{% endtrans %} : {{eleve.classe}}</p>
    <p class="card-text">{% trans %}Date de naissance{% endtrans %} : {{eleve.dateNaissance|date('d-m-Y')}}</p>
    <p class="card-text">{% trans %}Numéro du parent{% endtrans %} : {{eleve.numeroParent}}</p>
    <p class="card-text">{% trans %}Montant payé{% endtrans %} : {{eleve.montant}}</p>
  </div>
  <div class="col-md-5">
  <div class="card-group">
  <div class="card">
    <img class="card-img-top" src="{{eleve.photo}}" alt="{{ eleve.nom }}">
    <div class="card-body">
      <h5 class="card-title">{{eleve.nom}} {{eleve.prenom}}</h5>
    </div>
  </div>
  </div>
  </div>
  </div>
  </div>
</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans %}Fermer{% endtrans %}</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="{{eleve.matricule}}editer">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{% trans %}Editer{% endtrans %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{{ path('editer',  {"id": eleve.id})}}">
      <input type="number" class="form-control" hidden="true" id="id" value="{{ eleve.id }}" name="id">
      <div class="modal-body">
      <div class="row">
          <div class="col-md-6">
          <div class="form-group">
            <label for="nom" class="col-form-label">{% trans %}Nom{% endtrans %}:</label>
            <input type="text" class="form-control" id="nom" value="{{ eleve.nom }}" name="nom">
          </div>
          </div>
          <div class="col-md-6">
          <div class="form-group">
            <label for="prenom" class="col-form-label">{% trans %}Prenom{% endtrans %}:</label>
            <input type="text" class="form-control" id="prenom" value="{{ eleve.prenom }}" name="prenom">
          </div>
          </div>
          </div>
          <div class="row">
          <div class="col-md-6">
          <div class="form-group">
            <label for="classe" class="col-form-label">Classe:</label>
            <select id="classe"  value="{{ eleve.classe }}" name="classe">
              <option></option>
              <option>Sil-A</option>
              <option>Sil-B</option>
              <option>Cp-A</option>
              <option>Cp-B</option>
              <option>CE1-A</option>
              <option>CE1-B</option>
              <option>CE2-A</option>
              <option>CE2-B</option>
              <option>CM1-A</option>
              <option>CM1-B</option>
              <option>CM2-A</option>
              <option>CM2-B</option>
            </select>
          </div>
          </div>
          <div class="col-md-6">
          <div class="form-group">
            <label for="date" class="col-form-label">{% trans %}Date de naissance{% endtrans %}:</label>
            <input type="date" id="date" name="date_naissance" value="{{ eleve.dateNaissance|date('Y-m-d') }}">
          </div>
          </div>
          </div>
          <div class="form-group">
            <label for="numero" class="col-form-label">{% trans %}Numéro du parent{% endtrans %}:</label>
            <input type="text" class="form-control" id="numero"  value="{{ eleve.numeroParent }}" name="numero_parent">
          </div>
          <div class="form-group">
            <label for="photo" class="col-form-label">{% trans %}Photo de l'élève{% endtrans %}:</label>
            <input type="file" class="form-control" id="photo" name="photo">
          </div>
          <div class="row">
          <div class="col-md-6">
          <div class="form-group">
            <label for="matricule" class="col-form-label">{% trans %}Matricule{% endtrans %}:</label>
            <input type="text" class="form-control" id="matricule" disabled value="{{ eleve.matricule }}" name="matricule">
          </div>
          </div>
          <div class="col-md-6">
          <div class="form-group">
            <label for="montant" class="col-form-label">{% trans %}Montant{% endtrans %}:</label>
            <input type="number" class="form-control" id="montant" disabled  value="{{ eleve.montant }}" name="montant">
          </div>
          </div>
          </div>
          </div>
          <div class="modal-footer">
          <button type="submit" class="btn btn-success">{% trans %}Enregistrer les modifications{% endtrans %}</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans %}Annuler{% endtrans %}</button>
          </div>
</div>
      </form>
    </div>
  </div>
</div>

<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="{{eleve.matricule}}supprimer">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{% trans %}Supprimer{% endtrans %}</h5>
        
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>{% trans %}Êtes vous sur de vouloir supprimer cet élève{% endtrans %} : {{ eleve.nom }}  {{ eleve.prenom }} ?</p>
      </div>
      
      <div class="modal-footer">
      <a type="button" href="{{ path('supprimer',  {"id": eleve.id})}}" class="btn btn-danger">{% trans %}Supprimer{% endtrans %}</a>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans %}Annuler{% endtrans %}</button>
        
      </div>
    </div>
  </div>
</div>
    {% endfor %}
  </tbody>
  
</table>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#inscrire">{% trans %}Inscrire un nouvel élève{% endtrans %}</button>

<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="inscrire">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{% trans %}Nouvelle inscription{% endtrans %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {{ form_start(form) }}
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6">
          <div class="form-group">
            {{ form_row(form.nom) }}
          </div>
          </div>
          <div class="col-md-6">
          <div class="form-group">
            {{ form_row(form.prenom) }}
          </div>
          </div>
          </div>
          <div class="row">
          <div class="col-md-6">
          <div class="form-group">
            {{ form_row(form.classe) }}
          </div>
          </div>
          <div class="col-md-6">
          <div class="form-group">
            {{ form_row(form.date_naissance) }}
          </div>
          </div>
          </div>
          <div class="form-group">
            {{ form_row(form.numero_parent) }}
          </div>
          <div class="form-group">
            {{ form_row(form.photo) }}
          </div>
          <div class="form-group">
            {{ form_row(form.montant) }}
          </div>
        </div>
        
      <div class="modal-footer">
        {{ form_row(form.Inscrire) }}
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans %}Annuler{% endtrans %}</button>
      </div>
      {{ form_end(form) }}
    </div>
  </div>
</div>


{% endblock %}